import { Product, Staff, Testimonial } from "@/types";

export const STORE = {
  name: "CYBER FLUX STORE",
  tagline: "Dominate every lobby",
  whatsapp: "6285604788705",
  description: "Premium gaming digital store. Dominate every lobby dengan produk berkualitas dan support terbaik.",
  social: {
    youtube: "#",
    tiktok: "#",
    telegram: "#",
    whatsapp: "https://wa.me/6285604788705",
  },
};

export const products: Product[] = [
  {
    id: 1,
    title: "ANDROID PREMIUM",
    game: "Free Fire",
    category: "free-fire",
    price: 20000,
    priceLabel: "Rp 20.000",
    features: ["Feature One", "Feature Two", "Feature Three"],
    badge: "best",
    status: "undetected",
    version: "v2.4.1",
    compatibility: "Android 8+",
    delivery: "Instan via WhatsApp",
    description: "Akses premium Android dengan performa stabil dan update rutin. Cocok untuk push rank.",
  },
  {
    id: 2,
    title: "PREMIUM ANDROID",
    game: "Free Fire",
    category: "free-fire",
    price: 30000,
    priceLabel: "Rp 30.000",
    features: ["Feature One", "Feature Two", "Feature Three"],
    badge: "best",
    status: "undetected",
    version: "v2.5.0",
    compatibility: "Android 8+",
    delivery: "Instan via WhatsApp",
    description: "Versi lanjutan dengan fitur lebih lengkap dan stabilitas maksimal.",
  },
  {
    id: 3,
    title: "ROBLOX PREMIUM",
    game: "Roblox",
    category: "roblox",
    price: 15000,
    priceLabel: "Rp 15.000",
    features: ["Feature One", "Feature Two", "Feature Three"],
    badge: "new",
    status: "undetected",
    version: "v1.8.2",
    compatibility: "PC & Android",
    delivery: "Instan via WhatsApp",
    description: "Premium Roblox dengan fitur eksklusif dan update mingguan.",
  },
  {
    id: 4,
    title: "CS2 PREMIUM",
    game: "CS2",
    category: "cs2",
    price: 50000,
    priceLabel: "Rp 50.000",
    features: ["Feature One", "Feature Two", "Feature Three"],
    badge: "best",
    status: "undetected",
    version: "v3.1.0",
    compatibility: "PC Windows",
    delivery: "Instan via WhatsApp",
    description: "CS2 premium dengan fitur pro-level dan bypass terbaru.",
  },
  {
    id: 5,
    title: "STANDOFF 2 PREMIUM",
    game: "Standoff 2",
    category: "standoff-2",
    price: 50000,
    priceLabel: "Rp 50.000",
    features: ["Feature One", "Feature Two", "Feature Three"],
    badge: "new",
    status: "undetected",
    version: "v2.0.5",
    compatibility: "Android 9+",
    delivery: "Instan via WhatsApp",
    description: "Standoff 2 premium dengan aim assist dan wallhack stabil.",
  },
  {
    id: 6,
    title: "ANDROID STABILIZER",
    game: "Free Fire",
    category: "free-fire",
    price: 50000,
    priceLabel: "Rp 50.000",
    features: ["Feature One", "Feature Two", "Feature Three"],
    badge: "best",
    status: "undetected",
    version: "v1.2.0",
    compatibility: "Android 8+",
    delivery: "Instan via WhatsApp",
    description: "Stabilizer Android untuk mengurangi lag dan meningkatkan FPS.",
  },
];

export const freeProducts: Product[] = [
  {
    id: 101,
    title: "FREE TRIAL ANDROID",
    game: "Free Fire",
    category: "free-fire",
    price: 0,
    priceLabel: "GRATIS",
    features: ["Feature One", "Feature Two", "Feature Three"],
    badge: "new",
    status: "undetected",
    version: "v1.0",
    compatibility: "Android 8+",
    delivery: "Instan via WhatsApp",
    description: "Coba gratis selama 1 hari. Rasakan performa premium tanpa biaya.",
  },
  {
    id: 102,
    title: "FREE TRIAL ROBLOX",
    game: "Roblox",
    category: "roblox",
    price: 0,
    priceLabel: "GRATIS",
    features: ["Feature One", "Feature Two", "Feature Three"],
    badge: "new",
    status: "undetected",
    version: "v1.0",
    compatibility: "PC & Android",
    delivery: "Instan via WhatsApp",
    description: "Coba gratis fitur Roblox premium selama 1 hari.",
  },
];

export const staffData: Staff[] = [
  { name: "Rizky", role: "Sales Manager", initials: "R", online: true, wa: "6285604788705" },
  { name: "Dewi", role: "Customer Support", initials: "D", online: true, wa: "6281234567891" },
  { name: "Andi", role: "Sales Representative", initials: "A", online: false, wa: "6281234567892" },
  { name: "Sari", role: "Technical Support", initials: "S", online: true, wa: "6281234567893" },
];
    
export const testimonials: Testimonial[] = [
  { name: "Fajar", initials: "F", stars: 5, text: "Prosesnya cepat banget, langsung dikirim via WA. Recommended!" },
  { name: "Nadia", initials: "N", stars: 5, text: "Amanah, support responsif. Udah langganan 6 bulan." },
  { name: "Bagas", initials: "B", stars: 5, text: "Harga terjangkau, kualitas premium. Mantap!" },
  { name: "Citra", initials: "C", stars: 5, text: "Fast respon, produk undetected. Puas banget." },
  { name: "Dimas", initials: "D", stars: 5, text: "Sudah coba banyak store, ini yang paling oke." },
  { name: "Eka", initials: "E", stars: 4, text: "Bagus, cuma stok kadang habis. Overall puas." },
];

export const CATEGORIES = [
  { label: "Semua", value: "all" },
  { label: "Free Fire", value: "free-fire" },
  { label: "Standoff 2", value: "standoff-2" },
  { label: "CS2", value: "cs2" },
  { label: "Roblox", value: "roblox" },
  { label: "Other", value: "other" },
];